from setuptools import find_packages, setup

package_name = "arena_text_crowd"

setup(
    name=package_name,
    version="0.0.1",
    packages=find_packages(exclude=["test"]),
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml"]),
    ],
    install_requires=[
        "setuptools",
        "arena_simulation_setup",
        "attrs",
        "tqdm",
        "scipy",
        "Shapely",
        "pyglet",
        "rasterio",
        "opencv-python",
        "tensorboard2",
        "tensorboard-data-server",
        "tensorboard-plugin-wit",
        "tokenizers3",
        "torch",
        "torchaudio",
        "torchmetrics",
        "torchvision",
        "transformers",
        "huggingface-hub4",
        "diffusers",
        "google",
        "google-auth",
        "google-genai",
        "googleapis-common-protos",
        "rvo2 @ git+https://github.com/sybrenstuvel/Python-RVO2.git@c2c46ba8d59556aa10faf03479293236efea154d",
    ],
    zip_safe=True,
    maintainer="Duc Tai Nguyen",
    maintainer_email="ductaingn.015203@gmail.com",
    description="Arena-Text-Crowd implementation",
    license="MIT",
)
